version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: ./.infrastructure/php/Dockerfile
    volumes:
      - ./app:/var/www/html
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
        - ./.infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
    depends_on:
      - php